CREATE TABLE employees (
employee_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
first_name VARCHAR2(50),
last_name VARCHAR2(50),
department_id NUMBER,
salary NUMBER(10,2),
hire_date DATE,
PRIMARY KEY (employee_id)
);